name: SBOM/SCA Scout

on:
  workflow_dispatch: 
    inputs:
      docker_image:
        description: 'The Docker image to scan'
        required: true
        default: 'ghcr.io/pavlosath/omegago:latest' 

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.event.inputs.docker_image }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,sbom
          image: ${{ github.event.inputs.docker_image }}
          exit-code: false
          sarif-file: sca_scout.sarif
